// <auto-generated />
namespace Starter.Infra.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class authentities : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(authentities));
        
        string IMigrationMetadata.Id
        {
            get { return "201607061229049_auth-entities"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
